Fix the wrapper script to support RHEL6

diff --git a/replicator/bin/replicator b/replicator/bin/replicator
--- a/replicator/bin/replicator
+++ b/replicator/bin/replicator
@@ -163,20 +163,24 @@ LOCKFILE="$LOCKDIR/$APP_NAME"
 pid=""
 
 # Resolve the location of the 'ps' command
-PSEXE="/usr/bin/ps"
-if [ ! -x "$PSEXE" ]
-then
-    PSEXE="/bin/ps"
+PSEXE="/usr/ucb/ps"
     if [ ! -x "$PSEXE" ]
     then
-        echo "Unable to locate 'ps'."
-        echo "Please report this message along with the location of the command on your system."
-        exit 1
+        PSEXE="/usr/bin/ps"
+        if [ ! -x "$PSEXE" ]
+        then
+            PSEXE="/bin/ps"
+            if [ ! -x "$PSEXE" ]
+            then
+                echo "Unable to locate 'ps'."
+                echo "Please report this message along with the location of the command on your system."
+                exit 1
+            fi
+        fi
     fi
-fi
 
 # Resolve the os
-DIST_OS=`uname -s | tr [:upper:] [:lower:] | tr -d [:blank:]`
+DIST_OS=`uname -s | tr [A-Z] [a-z] | tr -d ' '`
 case "$DIST_OS" in
     'sunos')
         DIST_OS="solaris"
@@ -193,17 +197,10 @@ case "$DIST_OS" in
     'unix_sv')
         DIST_OS="unixware"
         ;;
+    'os/390')
+        DIST_OS="zos"
+        ;;
 esac
-
-# For Solaris ensure that /usr/ucb/ps is available.
-if [ "$DIST_OS" = "solaris" ]; then
-    if [ ! -x "/usr/ucb/ps" ]
-    then
-        echo "Solaris installations require /usr/ucb/ps to be available"
-        echo "Please report this message along with your system configuration."
-        exit 1
-    fi
-fi
 
 # Resolve the architecture
 if [ "$DIST_OS" = "macosx" ]
@@ -211,36 +208,83 @@ then
     DIST_ARCH="universal"
 else
     DIST_ARCH=
-    DIST_ARCH=`uname -p 2>/dev/null | tr [:upper:] [:lower:] | tr -d [:blank:]`
+    DIST_ARCH=`uname -p 2>/dev/null | tr [A-Z] [a-z] | tr -d ' '`
     if [ "X$DIST_ARCH" = "X" ]
     then
         DIST_ARCH="unknown"
     fi
     if [ "$DIST_ARCH" = "unknown" ]
     then
-        DIST_ARCH=`uname -m 2>/dev/null | tr [:upper:] [:lower:] | tr -d [:blank:]`
+        DIST_ARCH=`uname -m 2>/dev/null | tr [A-Z] [a-z] | tr -d ' '`
     fi
     case "$DIST_ARCH" in
-        'amd64' | 'athlon' | 'i386' | 'i486' | 'i586' | 'i686' | 'x86_64')
+        'athlon' | 'i386' | 'i486' | 'i586' | 'i686')
             DIST_ARCH="x86"
+            if [ "${DIST_OS}" = "solaris" ] ; then
+                DIST_BITS=`isainfo -b`
+            else
+                DIST_BITS="32"
+            fi
             ;;
-        'ia32' | 'ia64' | 'ia64n' | 'ia64w')
+        'amd64' | 'x86_64')
+            DIST_ARCH="x86"
+            DIST_BITS="64"
+            ;;
+        'ia32')
             DIST_ARCH="ia"
+            DIST_BITS="32"
+            ;;
+        'ia64' | 'ia64n' | 'ia64w')
+            DIST_ARCH="ia"
+            DIST_BITS="64"
             ;;
         'ip27')
             DIST_ARCH="mips"
+            DIST_BITS="32"
             ;;
         'power' | 'powerpc' | 'power_pc' | 'ppc64')
+            if [ "${DIST_ARCH}" = "ppc64" ] ; then
+                DIST_BITS="64"
+            else
+                DIST_BITS="32"
+            fi
             DIST_ARCH="ppc"
+            if [ "${DIST_OS}" = "aix" ] ; then
+                if [ `getconf KERNEL_BITMODE` -eq 64 ]; then
+                    DIST_BITS="64"
+                else
+                    DIST_BITS="32"
+                fi
+            fi
             ;;
         'pa_risc' | 'pa-risc')
             DIST_ARCH="parisc"
+            if [ `getconf KERNEL_BITS` -eq 64 ]; then
+                DIST_BITS="64"
+            else
+                DIST_BITS="32"
+            fi    
             ;;
-        'sun4u' | 'sparcv9')
+        'sun4u' | 'sparcv9' | 'sparc')
             DIST_ARCH="sparc"
+            DIST_BITS=`isainfo -b`
+            if [ ! -f /usr/lib/libm.so.2 -a "${DIST_BITS}" = "32" ]; then
+                ln -s /usr/lib/libm.so.1 /usr/lib/libm.so.2
+            elif [ ! -f /usr/lib/sparcv9/libm.so.2 -a "${DIST_BITS}" = "64" ]; then
+                ln -s /usr/lib/sparcv9/libm.so.1 /usr/lib/sparcv9/libm.so.2
+            fi
             ;;
-        '9000/800')
+        '9000/800' | '9000/785')
             DIST_ARCH="parisc"
+            if [ `getconf KERNEL_BITS` -eq 64 ]; then
+                DIST_BITS="64"
+            else
+                DIST_BITS="32"
+            fi
+            ;;
+        '2097')
+            DIST_ARCH="390"
+            DIST_BITS="32"
             ;;
     esac
 fi
@@ -263,15 +307,16 @@ outputFile() {
 }
 
 # Decide on the wrapper binary to use.
-# If a 32-bit wrapper binary exists then it will work on 32 or 64 bit
-#  platforms, if the 64-bit binary exists then the distribution most
-#  likely wants to use long names.  Otherwise, look for the default.
-WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+# If the bits of the OS could be detected, we will try to look for the
+#  binary with the correct bits value.  If it doesn't exist, fall back
+#  and look for the 32-bit binary.  If that doesn't exist either then
+#  look for the default.
+WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-$DIST_BITS"
 if [ -x "$WRAPPER_TEST_CMD" ]
 then
     WRAPPER_CMD="$WRAPPER_TEST_CMD"
 else
-    WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+    WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
     if [ -x "$WRAPPER_TEST_CMD" ]
     then
         WRAPPER_CMD="$WRAPPER_TEST_CMD"
@@ -279,8 +324,11 @@ else
         if [ ! -x "$WRAPPER_CMD" ]
         then
             echo "Unable to locate any of the following binaries:"
-            outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-            outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+            outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-$DIST_BITS"
+            if [ ! "$DIST_BITS" = "32" ]
+            then
+                outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+            fi
             outputFile "$WRAPPER_CMD"
             exit 1
         fi
